"""Repository for PasswordResetToken persistence operations."""

import hashlib
from datetime import UTC, datetime

from sqlmodel import Session, select

from ..models.password_reset import PasswordResetToken


def _hash_token(raw_token: str) -> str:
    """
    Return the SHA-256 hex digest of a raw token string.

    Args:
        raw_token: Plain-text token to hash.

    Returns:
        64-character hex string.
    """
    return hashlib.sha256(raw_token.encode()).hexdigest()


class PasswordResetTokenRepository:
    """Data-access layer for PasswordResetToken rows."""

    def __init__(self, session: Session) -> None:
        """
        Initialise the repository with a database session.

        Args:
            session: Active SQLModel session.
        """
        self._session = session

    def create(self, raw_token: str, email: str, expires_at: str) -> PasswordResetToken:
        """
        Persist a new password-reset token record.

        Args:
            raw_token: Plain-text token generated by the caller.
            email: Email address the reset was requested for.
            expires_at: ISO-8601 string of the expiry time.

        Returns:
            Persisted PasswordResetToken instance.
        """
        record = PasswordResetToken(
            token_hash=_hash_token(raw_token),
            email=email,
            created_at=datetime.now(UTC).isoformat(),
            expires_at=expires_at,
        )
        self._session.add(record)
        self._session.commit()
        self._session.refresh(record)
        return record

    def get_valid(self, raw_token: str) -> PasswordResetToken | None:
        """
        Return an unused, non-expired token record matching the raw token.

        Args:
            raw_token: Plain-text token to look up.

        Returns:
            Matching PasswordResetToken, or None if not found / invalid.
        """
        token_hash = _hash_token(raw_token)
        now_iso = datetime.now(UTC).isoformat()

        statement = select(PasswordResetToken).where(
            PasswordResetToken.token_hash == token_hash,
            PasswordResetToken.used_at.is_(None),  # type: ignore[union-attr]
            PasswordResetToken.expires_at > now_iso,
        )
        return self._session.exec(statement).first()

    def mark_used(self, record: PasswordResetToken) -> None:
        """
        Mark a token as consumed so it cannot be reused.

        Args:
            record: The PasswordResetToken to invalidate.
        """
        record.used_at = datetime.now(UTC).isoformat()
        self._session.add(record)
        self._session.commit()
